import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navbar">
          <div className="navbar-brand">
            <h1>CIS</h1>
          </div>
          <ul className="navbar-links">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/pokemon">Pokemon</Link></li>
            <li><Link href="/student">About Me</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}